name: API Tests (Postman + Newman)

on:
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Start backend server
        working-directory: backend
        run: |
          npm run start &
          sleep 10

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman collection
        working-directory: backend
        run: |
          newman run postman/ShiftManagement.postman_collection.json \
          --environment postman/ShiftManagement.postman_environment.json \
          --reporters cli,json \
          --reporter-json-export newman-report.json

      - name: Upload Newman report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: backend/newman-report.json

      # Comment Newman summary on PR
      - name: Comment Newman summary on PR
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            const reportPath = 'backend/newman-report.json';
            if (!fs.existsSync(reportPath)) {
              console.log('Newman report not found');
              return;
            }

            const report = JSON.parse(fs.readFileSync(reportPath));
            const stats = report.run.stats;

            const summary = `
            ## Newman API Test Results

            **Assertions**
            - Passed: ${stats.assertions.total - stats.assertions.failed}
            - Failed: ${stats.assertions.failed}
            - Total: ${stats.assertions.total}

            **Requests**
            - Total: ${stats.requests.total}
            - Failed: ${stats.requests.failed}

            Duration: ${report.run.timings.completed - report.run.timings.started} ms
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });
